name: CI

on: 
  push:
    paths-ignore: 
    - 'README.md'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update README.md
      run: ./utils/indexer.sh > README.md
    - name: Commit files
      run: |
        git config --global user.email "chad@chadlavimoniere.com"
        git config --global user.name "Chad Lavimoniere (CI)"
        git commit -m "Update README" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ secrets.GITHUB_REF }}
