name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update README.md
      run: |
        ./utils/indexer.sh > README.md
        git config --global user.email "chad@chadlavimoniere.com"
        git config --global user.name "Chad Lavimoniere (CI)"
        if [ "$(git status --porcelain)" ]; then
          git commit -am "update README" && git push
        fi
